server:
  port: ${PORT}

spring:
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: reminisce
  datasource:
    url: ${RDB_URL}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL}
    open-in-view: ${OPEN_IN_VIEW}
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SZIE}
      max-request-size: ${MAX_REQUEST_SIZE}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLE}
    path: ${API_DOCS_PATH}
    version: openapi_3_0
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLE}
  writer-with-default-pretty-printer: ${SWAGGER_UI_WRITER_WITH_DEFAULT_PRETTY_PRINTER}

jwt:
  access-token-expired: ${ACCESS_TOKEN_EXPIRED}
  refresh-token-expired: ${REFRESH_TOKEN_EXPIRED}
  secret:
    key: ${JWT_SECRET_KEY}

file:
  storage:
    path: ${FILE_STORAGE_PATH}
    cache-period: ${FILE_STORAGE_CACHE_PERIOD}

child:
  policy:
    max-per-guardian: ${CHILD_MAX_PER_GUARDIAN:3}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: ${KAKAO_TOKEN_URI}
    user-info-uri: ${KAKAO_USER_INFO_URI}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    token-uri: ${GOOGLE_TOKEN_URI}
    user-info-uri: ${GOOGLE_USER_INFO_URI}

LOG_HOST: ${LOG_HOST}
LOG_INDEX_ID: ${LOG_INDEX_ID}
NODE_ID: ${NODE_ID}
