server:
  port: 8080

spring:
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
  config:
    activate:
      on-profile: default
  application:
    name: boilerplate
  datasource:
    url: jdbc:postgresql://localhost:5432/boilerplate
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    root: info

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    version: openapi_3_0
  swagger-ui:
    enabled: true
  writer-with-default-pretty-printer: true

jwt:
  access-token-expired: 8640000
  refresh-token-expired: 1209600000
  secret:
    key: dsfighOIDGIosirdjgsxocivOEDISgvjvcpoEDOSosdifvgjoiODISsdfoigvj

file:
  storage:
    path: /Users/krince/Desktop/krince/boilerplate-files
    cache-period: 3600