package com.krince.reminisce.shared.response

enum class ExceptionResponseCode(
    override val isSuccess: Boolean,
    override val code: Int,
    override val detailCode: String,
    override val httpStatus: String,
    override val message: String,
) : ResponseCode {
    BAD_REQUEST(false, 400, "BR-000", "Bad Request", "잘못된 요청입니다."),
    INVALID_DTO_PARAMETER(false, 400, "BR-001", "Invalid Dto Parameter", "요청 값이 올바르지 않습니다.(dto 검증 오류)"),
    REQUIRE_NOT_BLANK(false, 400, "BR-002", "Require Not Blank", "해당 value object는 비어있을 수 없습니다."),
    REQUIRE_START_WITH(false, 400, "BR-003", "Require Start With", "해당 value object는 특정한 값으로 시작해야합니다."),
    REQUIRE_FILE_EXTENSION(false, 400, "BR-004", "Require File Extension", "확장자명이 없습니다."),
    INVALID_FILE_EXTENSION(false, 400, "BR-005", "Invalid File Extension", "올바르지 않은 파일 확장자입니다."),
    INVALID_MULTIPART_FILE(false, 400, "BR-006", "Invalid Multipart File", "올바르지 않은 파일입니다."),
    INVALID_EMAIL_FORMAT(false, 400, "BR-007", "Invalid Email Format", "올바르지 않은 이메일 형식입니다."),
    INVALID_NICKNAME_LENGTH(false, 400, "BR-008", "Invalid Nickname Length", "닉네임 길이가 올바르지 않습니다."),
    INVALID_CHILD_NICKNAME_LENGTH(false, 400, "BR-013", "Invalid Child Nickname Length", "아이 애칭 길이가 올바르지 않습니다."),
    INVALID_BIRTH_YEAR(false, 400, "BR-014", "Invalid Birth Year", "출생연도가 올바르지 않습니다."),
    UNAUTHORIZED(false, 401, "UA-000", "Unauthorized", "인증 정보가 올바르지 않습니다."),
    INVALID_TOKEN(false, 401, "UA-001", "Invalid Token", "유효하지 않은 토큰입니다."),
    EMPTY_TOKEN(false, 401, "UA-002", "Empty Token", "토큰이 없습니다."),
    EXPIRED_TOKEN(false, 401, "UA-003", "Expired Token", "만료된 토큰입니다."),
    WRONG_TOKEN(false, 401, "UA-004", "Expired Token", "토큰 형식을 확인해주세요."),
    LOGGED_OUT_TOKEN(false, 401, "UA-006", "Logged Out Token", "로그아웃된 토큰입니다."),
    UNAUTHORIZED_REFRESH_TOKEN(false, 402, "URT-000", "Unauthorized Refresh Token", "리프레시 토큰 정보가 올바르지 않습니다."),
    EXPIRED_REFRESH_TOKEN(false, 402, "URT-001", "Expired Refresh Token", "만료된 리프레시 토큰입니다."),
    INVALID_REFRESH_TOKEN(false, 402, "URT-002", "Invalid Refresh Token", "유효하지 않은 리프레시 토큰입니다."),
    EMPTY_REFRESH_TOKEN(false, 402, "URT-003", "Empty Refresh Token", "리프레시 토큰이 없습니다."),
    FORBIDDEN(false, 403, "FBD-000", "Forbidden", "해당 리소스에 접근 권한이 없습니다."),
    NOT_FOUND(false, 404, "NF-000", "Not Found", "리소스가 존재하지 않습니다."),
    NOT_FOUND_USER(false, 404, "NF-001", "Not Found User", "회원이 존재하지 않습니다."),
    NOT_FOUND_CHILD(false, 404, "NF-002", "Not Found Child", "아이가 존재하지 않습니다."),
    NOT_FOUND_STORY(false, 404, "NF-003", "Not Found Story", "이야기가 존재하지 않습니다."),
    CONFLICT(false, 409, "CF-000", "Conflict", "현재 리소스 상태와 충돌하여 처리할 수 없습니다."),
    BUSINESS_RULE_VIOLATION(false, 422, "BRV-000", "Business Rule Violation", "도메인 정책에 의해 실행할 수 없습니다."),
    CHILD_LIMIT_EXCEEDED(false, 422, "BRV-001", "Child Limit Exceeded", "등록 가능한 아이 수를 초과했습니다."),
    CONSENT_REQUIRED(false, 422, "BRV-002", "Consent Required", "법정대리인 동의가 없어 세션을 시작할 수 없습니다."),
    STT_TRANSCRIPTION_FAILED(false, 422, "BRV-003", "STT Transcription Failed", "음성 인식에 실패해 발화를 저장할 수 없습니다."),
    INTERNAL_SERVER_ERROR(false, 500, "ISR-000", "Internal Server Error", "서버 에러입니다. 개발자에게 문의해주세요."),
    BAD_GATEWAY(false, 502, "BG-000", "Bad Gateway", "게이트웨이 오류입니다."),
    SOCIAL_AUTH_FAILED(false, 502, "BG-002", "Social Auth Failed", "소셜 인증에 실패했습니다."),
}
